### ISSUE TITLE
SS4 branch

### ISSUE THREAD

**Issue by adrian-stein** [symbiote/silverstripe-grouped-cms-menu#28]
Is there going to get an SS4 branch?

**Comment by nyeholt** [comment]
Eventually - I think it's on our list of things for sometime before the end of the year.

**Comment by adrian-stein** [comment]
If you want and I have time I may be able to covert it and provide a PR if you are keen?

**Comment by jkRoberts** [comment]
Is there any further timeline around when there will be a SS4 update?

**Comment by nglasl** [comment]
Hey @adrian-stein and @jkRoberts, I just wanted to give you two an update on this one. While an SS4 upgrade is on our radar, we currently don't have a timeline around when it will actually happen (there are a few other modules which are higher priority at the moment). If you do happen to find the time (or anyone else who happens to stumble across this), a PR would be warmly welcomed :)

**Comment by nglasl** [comment]
I'm currently reviewing https://github.com/symbiote/silverstripe-grouped-cms-menu/pull/30 (as per the comments), but will close this issue to keep all discussions and conversations in the single thread (under the pull request). If there's reason to keep the issue open separately, please let me know. The important thing is that we link the two for historical purposes.
