### ISSUE TITLE
Not using translated title when grouped

### ISSUE THREAD

**Issue by sanderha** [symbiote/silverstripe-grouped-cms-menu#38]
In SS you can translate a ModelAdmin's menutitle like this:
```
  Orders\Admin\OrdersAdmin:
    MENUTITLE: 'Ordrer'
```
This module does not respect that, it simply uses `$class::create()->config()->get('menu_title')`, which will return the non-translated menutitle.
To have it fallback properly to original functionality, we can use this instead:
```
LeftAndMain::menu_title($code)
```

**Comment by nglasl** [comment]
Nice catch :)

**Comment by nglasl** [comment]
Will close this one too as I review the PR.
