### ISSUE TITLE
Upgrade to SilverStripe 5

### ISSUE THREAD

**Issue by kevingroeger** [symbiote/silverstripe-grouped-cms-menu#45]
There already is a PR here from someone: https://github.com/symbiote/silverstripe-grouped-cms-menu/pull/44 

Would be great to get it underway soonish

**Comment by kevingroeger** [comment]
Just added another PR and added the suggestions in the comments within #44 

See here: https://github.com/symbiote/silverstripe-grouped-cms-menu/pull/46

**Comment by kevingroeger** [comment]
@kinglozzer 

Could you merge this PR please? I tested this thoroughly on both 4.13 and 5.0.

No errors, warnings or deprecations found. Everything works fine

**Comment by kevingroeger** [comment]
Woops, sorry. Thought you were a maintainer. My bad.

I'm trying @nglasl then, pretty sure they do have merge access.

**Comment by nglasl** [comment]
Hi @kevingroeger I'm no longer a maintainer sorry. Sounds exciting though 🙂

**Comment by kevingroeger** [comment]
Hey @nglasl - sorry for another ping - do you know who is maintaining this repo now? This is the last package that I need upgraded in order to be able to use SilverStripe 5 in prod. Would be really nice if I knew who I could ask. 

If I can't find anyone I might just keep my fork and publish it on packagist myself.. :/

**Comment by nglasl** [comment]
I'm not sure sorry @kevingroeger, I was going to suggest looking [here](https://github.com/orgs/symbiote/people) but it's showing nobody 😅

**Comment by michalkleiner** [comment]
@kevingroeger you don't need a fork on packagist to be able to use that fork in your composer.json file, just specify the repo in the `repositories` section and it would pick it up over the packagist-published package.

**Comment by kevingroeger** [comment]
@michalkleiner Yes, I know. That's what I am currently doing. But I don't like to use that in prod. I'd rather use a repo that receives updates. 

If this repo is abandoned, I would just release mine for the sake of continuing the project and to have a place for people to raise issues and create PRs.
